### ISSUE TITLE
Move hardcoded values from CustomAdapter to HardcodedProvisioner

### ISSUE THREAD

**Issue by biels** [biels/FGCAlarm#10]
And hardcode everything else

**Comment by biels** [comment]
@polvallsortiz , @joansanchez You should take care of that, follow the example in SampleHardcodedProvisioner to implement the `void provision()` function in class SampleHardcodedProvisioner.
Everything is located under package com.fgcalarm.model.provisioning.provisioners.
CustomAdapter is an activity.

**Comment by polvallsortiz** [comment]
Please @biels tell us what has to be done in this issue so we can develop it

**Comment by biels** [comment]
While in the branch `dev-provisioning`, you have to do what's expalined above.
You have to implement the provisioning in the red one basing in the green one:
![image](https://cloud.githubusercontent.com/assets/5158960/20690735/9528c8aa-b5cc-11e6-9a5a-6e859f8b9b5d.png)

**Comment by biels** [comment]
You have to use `Line` and `Station` constructor:
`Station e1 = stationRepository.save(new Station(null, "Estació1", new Location(41.345D, 42.443D), linesE1));`
`Line l3 = lineRepository.save(new Line(null, "L3", Color.GREEN));`

Where `new Location(41.345D, 42.443D)` contains gps lat and long

**Comment by polvallsortiz** [comment]
@biels Harcoded Finished and Pending of Review (ERRORS in colours of the lines). Is up tu you to close the issue

**Comment by biels** [comment]
Everything is correct. However we should consider changing entities to hold an icon instead of a text + color. Opening an isuue for that
