### ISSUE TITLE
Rebase dev-frontend onto develop

### ISSUE THREAD

**Issue by biels** [biels/FGCAlarm#12]
@polvallsortiz Check that everything is as expected

**Comment by biels** [comment]
@polvallsortiz Can the current `dev-frontend-rebased` branch be accepted as the current implementation of the frontend?

**Comment by polvallsortiz** [comment]
@biels It can be accepted, except the STATUS BAR Color, that has to be transparent

**Comment by biels** [comment]
Okay, going to merge it into develop. It does not need to be perfect, just to not have lost anything it alredy had before rebasing.

**Comment by polvallsortiz** [comment]
OK, if you want to close the issue is up to you @biels

**Comment by biels** [comment]
Merged to `develop`
