### ISSUE TITLE
Update Line entity to hold icon instead or in addition to color

### ISSUE THREAD

**Issue by biels** [biels/FGCAlarm#14]

**Comment by biels** [comment]
We could just get icons from an asset folder by naming each icon with the exact name of the line in lowercase.

**Comment by polvallsortiz** [comment]
@biels @biels Now I would resolve that, creating a lines icon folder

**Comment by biels** [comment]
@polvallsortiz Exactly, create a folder under resources that contains files named `[linename].png`. For example, `l1.png`

**Comment by biels** [comment]
Are icons finally working as intended?

**Comment by biels** [comment]
Okay, closing
