### ISSUE TITLE
Change Notification Bar

### ISSUE THREAD

**Issue by polvallsortiz** [biels/FGCAlarm#5]
Change Notification Bar colour to make it transparent, now is blue.

**Comment by biels** [comment]
Is this done @polvallsortiz ? If it is, please close.

**Comment by polvallsortiz** [comment]
@biels Not yet

**Comment by polvallsortiz** [comment]
@biels I don't know how to do it, please assign it to @jordiae

**Comment by polvallsortiz** [comment]
Is correct in black color #closing
